### ISSUE TITLE
My pull request got combined with yours

### ISSUE THREAD

**Issue by SomeOrdinaryBro** [mshajid/CodeCraft#14]
My pull request got combined with your request and when i merged yours, it got got merged together. please look into this

**Comment by SomeOrdinaryBro** [comment]
I have reveted the pull please review

**Comment by SomeOrdinaryBro** [comment]
I reverted the merge - if your review that and merge it that would be cool. But its going to main (is that fine?)

**Comment by mshajid** [comment]
fine..
