### ISSUE TITLE
No Installations Images

### ISSUE THREAD

**Issue by mshajid** [mshajid/CodeCraft#24]
We've to embed the installation images for **this URL**: https://github.com/mshajid/CodeCraft/blob/main/Before%20You%20Start/4.%20Git%20&%20GitHub%20Mastery.md#learning-path-git-and-github-mastery. 

**Discussion**: _we will discuss this on VC how to come up with the installation instruction for Git._ Open up this issue thread until it's resolved.

**Comment by SomeOrdinaryBro** [comment]
Thanks for pointing this, was a bit lazy light night and wrote it in my to do list to update it today. will embed the pics today ;)

**Comment by SomeOrdinaryBro** [comment]
Added the images and few changes to the installation section - vids and other improvements.
