### ISSUE TITLE
Wrong image

### ISSUE THREAD

**Issue by SomeOrdinaryBro** [mshajid/CodeCraft#28]
on git installation section - step 14
image is duplicated, i will change it with the next PR with a big change.

**Comment by mshajid** [comment]
Alright. once completed let me know through VC

**Comment by SomeOrdinaryBro** [comment]
Alrighty

**Comment by SomeOrdinaryBro** [comment]
@mshajid this issue is fixed. let me know once ur PR is done. ill send my Req
