### ISSUE TITLE
Better If you use a another word

### ISSUE THREAD

**Issue by mshajid** [mshajid/CodeCraft#39]
Link: Python 101 - Mastering Python Fundamental, In this section, Better if we have replace the word "**Course**" with some other word since we're not providing the course.

**Comment by SomeOrdinaryBro** [comment]
What do you think about walkthrough or tutorial ?

**Comment by mshajid** [comment]
> What do you think about walkthrough or tutorial ?

will think about the word by this week, until then let's complete the content for now neh!

**Comment by SomeOrdinaryBro** [comment]
yeah

**Comment by SomeOrdinaryBro** [comment]
This is fixed.
