### ISSUE TITLE
Codecrafting Corner

### ISSUE THREAD

**Issue by mshajid** [mshajid/CodeCraft#41]
Instead of **Corner**, we have to come up with a new name I guess? Let me know @SomeOrdinaryBro thoughts about this?

**Comment by SomeOrdinaryBro** [comment]
Yeah, were not going to stick with the code crafting `**corner**`. its just a temp name. will come up with something new today 👍🏾

**Comment by SomeOrdinaryBro** [comment]
@mshajid What do you think about:

1. Start your programming journey
2. CodeQuest
3. Learn to Code
4. CodeCrafting

if you have any other suggestions let me know?

**Comment by SomeOrdinaryBro** [comment]
@mshajid any ideas?

**Comment by mshajid** [comment]
Code Crafting is better and i'm resolving this issue @SomeOrdinaryBro
